services:
  - type: web
    name: book-review-api
    env: python
    buildCommand: ""
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
